[package]
name = "ronde"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35", features = ["full"] }
futures = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.9"
clap = { version = "4.1", features = ["derive"]}
thiserror = "1"
maud = "0.26"
