[package]
name = "ronde"
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true


[dependencies]
ronde_lib = { path = "../ronde_lib" }
futures = "0.3"
tokio.workspace = true
